spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mysql?serverTimezone=UTC&useSSL=false
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
server:
#  ssl:
#        enabled: true  #开启ssl验证
#        key-store : classpath:keystore.p12 #证书文件位置
#        key-store-password : 123456  #上面的密钥口令
#        key-store-type : PKCS12   #storetype 上面的类型
#        key-alias : tomcat    #tomcat上面的alias  别名
  port: 8089